---
version: "2.1"
services:
  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PASSWORD=PASSWORD
      - CUSTOM_RESULTS=false
      - DB_TYPE=sqlite
    volumes:
      - /services/librespeed/config:/config
    restart: unless-stopped
    networks: 
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.rule=Host(`librespeed.local`)"
      - "traefik.http.routers.librespeed.entrypoints=web"

networks: 
  lan:
    external: true
