# Apps

- name: Add favorite apps
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['org.mozilla.firefox.desktop', 'code.desktop', 'im.riot.Riot.desktop', 'com.discordapp.Discord.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop']"
    state: present

- name: Create autostart directory
  ansible.builtin.file:
    path: ~/.config/autostart
    state: directory

- name: Set Startup applications
  ansible.builtin.file:
    state: link
    force: yes
    src: "{{ ansible_env.PWD }}/roles/workstation/files/gnome/{{ item }}"
    dest: ~/.config/autostart/{{ item }}
  with_items:
    - com.discordapp.Discord.desktop
    - com.nextcloud.desktopclient.nextcloud.desktop
    - im.riot.Riot.desktop

# Keybindings

- name: Switch to left workspace
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left"
    value: "['<Super><Control>Left']"
    state: present

- name: Switch to right workspace
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right"
    value: "['<Super><Control>Right']"
    state: present

- name: Switch to app space to left workspace
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left"
    value: "['<Super><Control>Home']"
    state: present

- name: Switch to app space to right workspace
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right"
    value: "['<Super><Control>End']"
    state: present

- name: Switch windows
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab']"
    state: present

- name: Close window
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/close"
    value: "['<Super>W']"
    state: present

- name: Screenshot
  community.general.dconf:
    key: "/org/gnome/shell/keybindings/show-screenshot-ui"
    value: "['<Shift><Super>S']"
    state: present

- name: Terminal shortcut binding
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Super>t'"
    state: present

- name: Terminal shortcut command
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'gnome-terminal'"
    state: present

- name: Terminal shortcut name
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'Terminal'"
    state: present

- name: System monitor shortcut binding
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
    value: "'<Control><Shift>Escape'"
    state: present

- name: System monitor shortcut command
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
    value: "'gnome-system-monitor'"
    state: present

- name: System monitor shortcut name
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
    value: "'System monitor'"
    state: present
