---

ansible_ssh_host: "{{ secret_alderaan_host }}"

# Playbook

mash_playbook_generic_secret_key: "{{ secret_mash_playbook_generic_secret_key }}"

# Override service names and directory path prefixes
mash_playbook_service_identifier_prefix: 'mash-nextcloud-'
mash_playbook_service_base_directory_name_prefix: 'nextcloud-'

# redis

redis_enabled: true
