version: "3.3"
services:
  mail:
    image: bytemark/smtp
    container_name: "plausible-mail"
    restart: unless-stopped
    networks: 
      - plausible

  plausible_db:
    image: postgres:12
    container_name: "plausible-postgres"
    restart: unless-stopped
    networks: 
      - plausible
    volumes:
      - ~/services/plausible/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    container_name: "plausible-clickhouse"
    restart: unless-stopped
    networks: 
      - plausible
    volumes:
      - ~/services/plausible/clickhouse/clickhouse:/var/lib/clickhouse
      - ~/services/plausible/clickhouse/config.d:/etc/clickhouse-server/config.d/logging.xml:ro
      - ~/services/plausible/clickhouse/users.d:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    container_name: "plausible"
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    networks: 
      - lan
      - plausible
    env_file:
      - ~/services/plausible/plausible/plausible-conf.env
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.plausible-http.entrypoints=web"
    - "traefik.http.routers.plausible-http.rule=Host(`analytics.codecaptured.com`)"
    - "traefik.http.routers.plausible-http.middlewares=plausible"
    - "traefik.http.middlewares.plausible.redirectscheme.scheme=https"
    - "traefik.http.routers.plausible.entrypoints=websecure"
    - "traefik.http.routers.plausible.rule=Host(`analytics.codecaptured.com`)"
    - "traefik.http.routers.plausible.tls=true"
    - "traefik.http.routers.plausible.tls.certresolver=letsEncrypt"
    - "traefik.http.services.plausible.loadbalancer.server.port=8000"

networks: 
  plausible:
  lan:
    external: true
