version: '2.1'
services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - ~/services/flame/data:/app/data
    networks: 
      - lan
    environment:
      - PASSWORD={{ secret_flame_password }}
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.flame-http.entrypoints=web"
    - "traefik.http.routers.flame-http.rule=Host(`home.codecaptured.com`)"
    - "traefik.http.routers.flame-http.middlewares=flame"
    - "traefik.http.middlewares.flame.redirectscheme.scheme=https"
    - "traefik.http.routers.flame.entrypoints=websecure"
    - "traefik.http.routers.flame.rule=Host(`home.codecaptured.com`)"
    - "traefik.http.routers.flame.tls=true"
    - "traefik.http.routers.flame.tls.certresolver=letsEncrypt"
    - "traefik.http.services.flame.loadbalancer.server.port=5005"

networks: 
  lan:
    external: true
