---

- block:
    - when: shell_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/shell.yml"
  tags:
    - setup-all
    - setup-shell

- block:
    - when: user_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/user.yml"
  tags:
    - setup-all
    - setup-user

- block:
    - when: system_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/system.yml"
  tags:
    - setup-all
    - setup-system

- block:
    - when: ssh_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/ssh.yml"
  tags:
    - setup-all
    - setup-ssh

- block:
    - when: reboot_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/reboot.yml"
  tags:
    - setup-all
    - setup-reboot
