- name: Update package index
  become: true
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install standard shell related packages. Used by other tasks
  become: true
  ansible.builtin.package:
    name:
      - sudo
      - gnupg2
    state: present
