- name: Create user
  ansible.builtin.user:
    name: matthew
    shell: /bin/bash

- name: Make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add user to wheel group
  ansible.builtin.user:
    name: matthew
    groups: wheel
    append: yes

- name: Set authorized keys
  ansible.posix.authorized_key:
    user: matthew
    state: present
    key: '{{ item }}'
  with_file:
    - ../common/files/mandalore/id_rsa.pub
    - ../common/files/corellia/id_rsa.pub
