{ ... }:

{
  imports = [
    ./acme.nix
    ./authelia-nginx.nix
    ./authelia.nix
    ./calibre-web-automated.nix
    ./common-config.nix
    ./common-workstation-config.nix
    ./firewall.nix
    ./flatpak.nix
    ./forgejo-oidc.nix
    ./forgejo.nix
    ./foundryvtt-router.nix
    ./foundryvtt.nix
    ./headscale.nix
    ./home-assistant-oidc.nix
    ./homepage.nix
    ./hugo-site.nix
    ./jellyfin-oidc.nix
    ./jellyfin.nix
    ./linode.nix
    ./lldap.nix
    ./manyfold.nix
    ./manyfold-oidc.nix
    ./mealie-oidc.nix
    ./mealie.nix
    ./miniflux-oidc.nix
    ./miniflux.nix
    ./namecheap-private-cert.nix
    ./nextcloud-oidc.nix
    ./nextcloud.nix
    ./nginx-recommended.nix
    ./ntfy.nix
    ./plymouth.nix
    ./postgresql.nix
    ./protonvpn-exit-node-losangeles.nix
    ./protonvpn-exit-node-miami.nix
    ./protonvpn-exit-node-seattle.nix
    ./security.nix
    ./silverbullet.nix
    ./ssh.nix
    ./tailscale.nix
    ./umami.nix
    ./uptime-kuma.nix
    ./user.nix
    ./vscode-remote-ssh.nix
    ./wallabag.nix
  ];
}
