# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  config,
  ...
}:

let
  cfg = config.flame;
in
{
  options = {
    flame.enable = lib.mkEnableOption "enable flame module";

    flame.domainName = lib.mkOption { type = lib.types.str; };
    flame.certHostDomainName = lib.mkOption { type = lib.types.str; };
    flame.dataDir = lib.mkOption { type = lib.types.str; };
  };

  config = lib.mkIf cfg.enable {

    services.nginx = {
      enable = true;
      virtualHosts."${cfg.domainName}" = {
        enableAuthelia = true;
        forceSSL = true;
        useACMEHost = cfg.certHostDomainName;
        locations."/" = {
          proxyPass = "http://127.0.0.1:5005";
        };
      };
    };

    # Create mount point for data directory
    systemd.tmpfiles.rules = [
      "d ${cfg.dataDir} 0755 root root"
    ];

    # Runtime
    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
    };

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces =
      let
        matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
      in
      {
        "${matchAll}".allowedUDPPorts = [ 53 ];
      };

    virtualisation.oci-containers.backend = "podman";

    # Containers
    virtualisation.oci-containers.containers."flame" = {
      image = "pawelmalak/flame";
      volumes = [
        "${cfg.dataDir}:/app/data:rw"
      ];
      ports = [
        "5005:5005/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=flame"
        "--network=flame_default"
      ];
    };
    systemd.services."podman-flame" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-flame_default.service"
      ];
      requires = [
        "podman-network-flame_default.service"
      ];
      partOf = [
        "podman-compose-flame-root.target"
      ];
      wantedBy = [
        "podman-compose-flame-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-flame_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f flame_default";
      };
      script = ''
        podman network inspect flame_default || podman network create flame_default
      '';
      partOf = [ "podman-compose-flame-root.target" ];
      wantedBy = [ "podman-compose-flame-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-flame-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
