# Auto-generated by compose2nix.
# Configuration https://manyfold.app/sysadmin/configuration.html

{
  pkgs,
  lib,
  config,
  ...
}:

let
  cfg = config.manyfold;
in
{
  options = {
    manyfold.enable = lib.mkEnableOption "enable manyfold module";

    manyfold.subDomainName = lib.mkOption { type = lib.types.str; };
    manyfold.baseDomainName = lib.mkOption { type = lib.types.str; };
    manyfold.certHostDomainName = lib.mkOption { type = lib.types.str; };

    manyfold.secretEnvFilePath = lib.mkOption { type = lib.types.str; };

    manyfold.dataDir = lib.mkOption { type = lib.types.str; };

    manyfold.oidcClientId = lib.mkOption { type = lib.types.str; };
    manyfold.authDomainName = lib.mkOption { type = lib.types.str; };

    manyfold.user = lib.mkOption {
      type = lib.types.str;
      default = "manyfold";
    };

    manyfold.group = lib.mkOption {
      type = lib.types.str;
      default = "manyfold";
    };

    manyfold.uid = lib.mkOption {
      type = lib.types.ints.unsigned;
      default = 976;
    };

    manyfold.gid = lib.mkOption {
      type = lib.types.ints.unsigned;
      default = 976;
    };

    manyfold.port = lib.mkOption {
      type = lib.types.port;
      default = 3214;
    };
  };

  config = lib.mkIf cfg.enable {
    services.nginx = {
      enable = true;
      virtualHosts."${cfg.subDomainName}.${cfg.baseDomainName}" = {
        forceSSL = true;
        useACMEHost = cfg.certHostDomainName;
        locations."/" = {
          proxyPass = "http://127.0.0.1:${builtins.toString cfg.port}";
        };
      };
    };

    # Create storage for actual media files
    systemd.tmpfiles.rules = [
      "d ${cfg.dataDir} 0755 ${cfg.user} ${cfg.group}"
      "d /tmp/${cfg.user} 0755 ${cfg.user} ${cfg.group}"
    ];

    # Runtime
    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
    };

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces =
      let
        matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
      in
      {
        "${matchAll}".allowedUDPPorts = [ 53 ];
      };

    virtualisation.oci-containers.backend = "podman";

    # Containers
    virtualisation.oci-containers.containers."manyfold-app" = {
      # The manyfold-solo image doesn't expect Redis
      image = "ghcr.io/manyfold3d/manyfold-solo:0.136.0";
      environment = {
        # It had issues parsing the host path with '/'
        DATABASE_URL = "postgresql://manyfold@%2Fvar%2Fpostgresql/manyfold";

        HTTPS_ONLY = "enabled";
        MULTIUSER = "enabled";

        PUBLIC_HOSTNAME = "${cfg.subDomainName}.${cfg.baseDomainName}";

        # Prevent the app from running as root within the container
        PUID = builtins.toString cfg.uid;
        PGID = builtins.toString cfg.gid;

        # This is set, as the files in the default (/tmp) seems to fail/not exist when the app starts up
        TMPDIR = "/usr/src/app/tmp";

        # OIDC settings
        OIDC_CLIENT_ID = cfg.oidcClientId;
        OIDC_ISSUER = "https://${cfg.authDomainName}";
        OIDC_NAME = "Authelia";
      };
      # Secrets
      environmentFiles = [
        cfg.secretEnvFilePath
      ];
      volumes = [
        "${cfg.dataDir}:/libraries:rw"
        "/run/postgresql:/var/postgresql:Z"

        # Rails seems to loose access to the tmp files otherwise, so here's a workaround
        "/tmp/${cfg.user}:/usr/src/app/tmp:rw"
      ];
      ports = [
        "${builtins.toString cfg.port}:3214/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--cap-add=CHOWN"
        "--cap-add=DAC_OVERRIDE"
        "--cap-add=SETGID"
        "--cap-add=SETUID"
        "--cap-drop=ALL"
        "--network-alias=app"
        "--network=manyfold_default"
        "--security-opt=no-new-privileges:true"
      ];
    };
    systemd.services."podman-manyfold-app" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-manyfold_default.service"
      ];
      requires = [
        "podman-network-manyfold_default.service"
      ];
      partOf = [
        "podman-compose-manyfold-root.target"
      ];
      wantedBy = [
        "podman-compose-manyfold-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-manyfold_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f manyfold_default";
      };
      script = ''
        podman network inspect manyfold_default || podman network create manyfold_default
      '';
      partOf = [ "podman-compose-manyfold-root.target" ];
      wantedBy = [ "podman-compose-manyfold-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-manyfold-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
      requires = [ "postgresql.service" ];
      after = [ "postgresql.service" ];
    };

    users.users = {
      ${cfg.user} = {
        isSystemUser = true;
        group = cfg.group;
        uid = cfg.uid;
      };
    };

    users.groups = {
      ${cfg.group} = {
        gid = cfg.gid;
      };
    };

    services.postgresql = {
      ensureDatabases = [ cfg.user ];
      ensureUsers = [
        {
          name = cfg.user;
          ensureDBOwnership = true;
        }
      ];
    };
  };
}
