{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.urshort;

  envLines =
    (lib.mapAttrsToList (name: uri: "URSHORT_STANDARD_URI_${name}=${uri}") cfg.standardMappings)
    ++ (lib.flatten (
      lib.imap0 (idx: mapping: [
        "URSHORT_PATTERN_REGEX_${builtins.toString idx}=${mapping.regex}"
        "URSHORT_PATTERN_URI_${builtins.toString idx}=${mapping.uri}"
      ]) cfg.patternMappings
    ));

  envFile = pkgs.writeTextFile {
    name = "urshort-env";
    text = lib.concatStringsSep "\n" envLines + "\n";
  };
in
{
  options.urshort = {
    enable = lib.mkEnableOption "urshort url shortener";

    domainName = lib.mkOption { type = lib.types.str; };

    standardMappings = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = ''
        Vanity URL mappings. Each attribute name becomes the short path,
        and the value is the redirect target URL.
      '';
    };

    patternMappings = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            regex = lib.mkOption {
              type = lib.types.str;
            };
            uri = lib.mkOption {
              type = lib.types.str;
            };
          };
        }
      );
      default = [ ];
      description = ''
        Regex-based URL pattern mappings. Each entry has a regex pattern
        and a target URI with capture group replacements.
      '';
    };

    port = lib.mkOption {
      type = lib.types.port;
      default = 54027;
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "urshort";
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "urshort";
    };

  };

  config = lib.mkIf cfg.enable {

    services.nginx = {
      enable = true;
      virtualHosts."${cfg.domainName}" = {
        forceSSL = true;
        enableACME = true;
        locations."/" = {
          proxyPass = "http://127.0.0.1:${builtins.toString cfg.port}";
        };
      };
    };

    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
    };

    virtualisation.oci-containers.backend = "podman";

    # Containers
    virtualisation.oci-containers.containers."urshort" = {
      image = "mirdaki/urshort:latest";
      environment = {
        URSHORT_PORT = "54027";
      };
      environmentFiles = [ envFile ];
      ports = [ "${builtins.toString cfg.port}:54027/tcp" ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=urshort"
        "--network=urshort_default"
      ];
    };

    systemd.services."podman-urshort" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "no";
      };
      after = [
        "podman-network-urshort_default.service"
      ];
      requires = [
        "podman-network-urshort_default.service"
      ];
      partOf = [
        "podman-compose-urshort-root.target"
      ];
      wantedBy = [
        "podman-compose-urshort-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-urshort_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f urshort_default";
      };
      script = ''
        podman network inspect urshort_default || podman network create urshort_default
      '';
      partOf = [ "podman-compose-urshort-root.target" ];
      wantedBy = [ "podman-compose-urshort-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-urshort-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };

    users = {
      users."${cfg.user}" = {
        isSystemUser = true;
        group = cfg.group;
      };
      groups."${cfg.group}" = { };
    };

  };
}
